### ISSUE TITLE
Doorway False Positive [Fly - NoFall Normal]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#96]
## How you trigger the false positive?
Stand in a doorway, get partially inside of the door and partially outside and spam the door while jumping. Watch the video.

## Verbose Message:
https://pastebin.com/raw/rusPeMPR

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgogPwly7oC8y57eaKA

## Server Infomation
**Matrix Version**: 1.7.5
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed

**Comment by ignPerformance** [comment]
Reopened. This bug still exists. https://1drv.ms/v/s!ApY4tKsF8vPUgogxu4ZmfGXxMKw3zQ

**Comment by jiangdashao** [comment]
Fixed
