### ISSUE TITLE
Right-Clicking on Blocks False Positive [Autoclicker]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#98]
## How you trigger the false positive?
Hold right-click on a FENCE.

## Verbose Message:
https://pastebin.com/raw/SjwEwfS7

## Server Infomation
**Matrix Version**: 1.8.2
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by ignPerformance** [comment]
Actually, this works for any door: https://1drv.ms/v/s!ApY4tKsF8vPUgogGOu3Br_JOpYVUFg

**Comment by jiangdashao** [comment]
Fixed

**Comment by ignPerformance** [comment]
This issue still works for these blocks: fences, cauldrons, placed signs

**Comment by ignPerformance** [comment]
This issue still works with fences.

**Comment by ignPerformance** [comment]
Reopened. This works on flower pots.

**Comment by ignPerformance** [comment]
Protected blocks that flag for autoclicker:

Chests, furnaces, brewing stands, hoppers, anvils, beds, dispensers, observers, trapped chests, redstone repeaters, redstone comparators, and shulker boxes.
